@echo off
REM Move unreferenced documents to trash folder

if not exist trash\archive_docs mkdir trash\archive_docs

move "AIJIAOYI_COMPLETE_FINAL.md" trash\archive_docs\
move "AIJIAOYI_FINAL_REPORT.md" trash\archive_docs\
move "API_FIXES_SUMMARY.md" trash\archive_docs\
move "API_TEST_REPORT.md" trash\archive_docs\
move "BACKEND_RESTART_COMPLETE.md" trash\archive_docs\
move "BINANCE_GAINER_FALLBACK_SOLUTION.md" trash\archive_docs\
move "BINANCE_RESTRICTION_SOLUTION.md" trash\archive_docs\
move "CONNECTION_STATUS.md" trash\archive_docs\
move "DATABASE_SCHEMA.md" trash\archive_docs\
move "DATA_STORAGE_POLICY.md" trash\archive_docs\
move "DEPLOYMENT_SUCCESS.md" trash\archive_docs\
move "DOCKER_INSTALL_GUIDE.md" trash\archive_docs\
move "DOCKER_SELENIUM_COMPLETE.md" trash\archive_docs\
move "EXCHANGE_CREDENTIALS_FEATURE.md" trash\archive_docs\
move "FINAL_SUMMARY.md" trash\archive_docs\
move "FIXES_SUMMARY.md" trash\archive_docs\
move "FRONTEND_FIX_SUCCESS.md" trash\archive_docs\
move "FRONTEND_TEST_REPORT.md" trash\archive_docs\
move "FRONTENT_API_FIX_COMPLETE.md" trash\archive_docs\
move "FUTURES_API_IMPLEMENTATION.md" trash\archive_docs\
move "FUTURES_ONLY_COMPLETE.md" trash\archive_docs\
move "GAINERS_DATA_FIX_COMPLETE.md" trash\archive_docs\
move "GAINER_HISTORY_REDIS_STRUCTURE.md" trash\archive_docs\
move "GAINER_TABLE_FIX_COMPLETE.md" trash\archive_docs\
move "HAMA_15M_FIX_COMPLETE.md" trash\archive_docs\
move "HAMA_ALGORITHM_FIXED.md" trash\archive_docs\
move "HAMA_ALGORITHM_SUCCESS.md" trash\archive_docs\
move "HAMA_API_FIX_COMPLETE.md" trash\archive_docs\
move "HAMA_AUTO_MONITOR_GUIDE.md" trash\archive_docs\
move "HAMA_AUTO_MONITOR_MYSQL.md" trash\archive_docs\
move "HAMA_BRAVE_AUTO_LOGIN_COMPLETE.md" trash\archive_docs\
move "HAMA_BRAVE_MONITOR_COMPLETE.md" trash\archive_docs\
move "HAMA_BRAVE_ONLY.md" trash\archive_docs\
move "HAMA_CACHE_AUTO_UPDATE.md" trash\archive_docs\
move "HAMA_CACHE_CONFIG.md" trash\archive_docs\
move "HAMA_CACHE_EXPLANATION.md" trash\archive_docs\
move "HAMA_CACHE_SUCCESS.md" trash\archive_docs\
move "HAMA_CROSS_DISPLAY_ISSUE.md" trash\archive_docs\
move "HAMA_EMA20_SUCCESS.md" trash\archive_docs\
move "HAMA_EMAIL_INTEGRATION_COMPLETE.md" trash\archive_docs\
move "HAMA_EMAIL_NOTIFICATION_GUIDE.md" trash\archive_docs\
move "HAMA_FIX.md" trash\archive_docs\
move "HAMA_FIX_FINAL.md" trash\archive_docs\
move "HAMA_FRONTEND_INTEGRATION_COMPLETE.md" trash\archive_docs\
move "HAMA_MARKET_FRONTEND_FIX.md" trash\archive_docs\
move "HAMA_MONITOR_COMPLETE.md" trash\archive_docs\
move "HAMA_MONITOR_RUNNING.md" trash\archive_docs\
move "HAMA_NO_LOGIN_COMPLETE.md" trash\archive_docs\
move "HAMA_ON_DEMAND.md" trash\archive_docs\
move "HAMA_PRICE_FIX.md" trash\archive_docs\
move "HAMA_RIGHT_PANEL_OCR.md" trash\archive_docs\
move "HAMA_SCREENSHOT_DEBUG.md" trash\archive_docs\
move "HAMA_SCREENSHOT_DISPLAY.md" trash\archive_docs\
move "HAMA_SCREENSHOT_DISPLAY_FIX.md" trash\archive_docs\
move "HAMA_SCREENSHOT_FIX.md" trash\archive_docs\
move "HAMA_SCREENSHOT_TOGGLE.md" trash\archive_docs\
move "HAMA_SIGNAL_DISPLAY_FIX.md" trash\archive_docs\
move "HAMA_SMART_EMAIL_NOTIFICATION.md" trash\archive_docs\
move "HAMA_SMART_REFRESH_COMPLETE.md" trash\archive_docs\
move "HAMA_SQLITE_PRIORITY.md" trash\archive_docs\
move "HAMA_SYMBOLS_REVERT.md" trash\archive_docs\
move "HAMA_TEST_REPORT.md" trash\archive_docs\
move "HAMA_TEST_SUMMARY_20260118.md" trash\archive_docs\
move "HAMA_WORKER_INTEGRATION.md" trash\archive_docs\
move "HYBRID_DEPLOYMENT_GUIDE.md" trash\archive_docs\
move "KLINE_FIX_SUMMARY.md" trash\archive_docs\
move "MULTI_EXCHANGE_COMPARISON.md" trash\archive_docs\
move "MULTI_EXCHANGE_PAGE_SUCCESS.md" trash\archive_docs\
move "MYSQL_SETUP_GUIDE.md" trash\archive_docs\
move "OCR_TEST_REPORT.md" trash\archive_docs\
move "PROXY_CONFIG_COMPLETE.md" trash\archive_docs\
move "PROXY_CONFIG_FIXED.md" trash\archive_docs\
move "PROXY_CONFIG_RESULT.md" trash\archive_docs\
move "PROXY_CONFIG_SUCCESS.md" trash\archive_docs\
move "REALTIME_PRICE_SOLUTION.md" trash\archive_docs\
move "REALTIME_PRICE_SUCCESS.md" trash\archive_docs\
move "REDIS_AND_BRAVE_SETUP.md" trash\archive_docs\
move "REDIS_DEPLOYMENT.md" trash\archive_docs\
move "REDIS_SCHEDULER_GUIDE.md" trash\archive_docs\
move "REDIS_SUCCESS_REPORT.md" trash\archive_docs\
move "RESTART_GUIDE.md" trash\archive_docs\
move "SCREENSHOT_CACHE_GUIDE.md" trash\archive_docs\
move "SCREENSHOT_FIX_GUIDE.md" trash\archive_docs\
move "SELENIUM_SETUP_COMPLETE.md" trash\archive_docs\
move "SMART_MONITOR_COMPLETE.md" trash\archive_docs\
move "SNTAX_ERROR_FIXED.md" trash\archive_docs\
move "SQLITE_THREAD_FIX.md" trash\archive_docs\
move "SSE_ALL_COINS_UPDATE_SUCCESS.md" trash\archive_docs\
move "SSE_FINAL_EXPLANATION.md" trash\archive_docs\
move "SSE_FINAL_FIX_REPORT.md" trash\archive_docs\
move "SSE_NGINX_FIX_SUCCESS.md" trash\archive_docs\
move "TIMEOUT_FIX_COMPLETE.md" trash\archive_docs\
move "TRADINGVIEW_AS_DATASOURCE.md" trash\archive_docs\
move "TRADINGVIEW_COIN_LEVEL_CACHE_COMPLETE.md" trash\archive_docs\
move "TRADINGVIEW_COMPLETE.md" trash\archive_docs\
move "TRADINGVIEW_COOKIES.md" trash\archive_docs\
move "TRADINGVIEW_INTEGRATION_COMPLETE.md" trash\archive_docs\
move "TRADINGVIEW_PLAYWRIGHT_IMPLEMENTATION.md" trash\archive_docs\
move "TRADINGVIEW_PYPPETEER_IMPLEMENTATION.md" trash\archive_docs\
move "TRADINGVIEW_SCANNER_ACCESS_GUIDE.md" trash\archive_docs\
move "TRADINGVIEW_SCANNER_AUTO_HAMA.md" trash\archive_docs\
move "TRADINGVIEW_SCANNER_DATA_TEST_REPORT.md" trash\archive_docs\
move "TRADINGVIEW_SCANNER_FINAL_SUCCESS.md" trash\archive_docs\
move "TRADINGVIEW_SCANNER_FRONTEND_INTEGRATION_COMPLETE.md" trash\archive_docs\
move "TRADINGVIEW_SCANNER_HAMA_FEATURE_COMPLETE.md" trash\archive_docs\
move "TRADINGVIEW_SCANNER_HAMA_RESTORED.md" trash\archive_docs\
move "TRADINGVIEW_SCANNER_HAMA_STATUS_UPDATE.md" trash\archive_docs\
move "TRADINGVIEW_SCANNER_INTEGRATION_SUCCESS.md" trash\archive_docs\
move "TRADINGVIEW_SCANNER_MA100_COLUMN.md" trash\archive_docs\
move "TRADINGVIEW_SCANNER_PAGE_READY.md" trash\archive_docs\
move "TRADINGVIEW_SCANNER_REDIS_CACHE_SUCCESS.md" trash\archive_docs\
move "TRADINGVIEW_SCANNER_SUCCESS.md" trash\archive_docs\
move "TRADINGVIEW_SCANNER_TABLE_SIMPLIFIED.md" trash\archive_docs\
move "TRADINGVIEW_SCANNER_THREE_MODES_TEST.md" trash\archive_docs\
move "TRADINGVIEW_WATCHLIST_API_COMPLETE.md" trash\archive_docs\
move "TRADINGVIEW_WATCHLIST_GUIDE.md" trash\archive_docs\
move "UPDATE_HAMA_MONITOR.md" trash\archive_docs\
move "VPN_PROXY_SUCCESS.md" trash\archive_docs\
move "启动脚本使用指南.md" trash\archive_docs\
