"""
预定义的币安USDT永续合约列表(已测试TradingView Scanner可用性)
共184个币种,已在TradingView Scanner中验证可用
测试日期: 2024-01-11
"""

# 经过TradingView Scanner测试验证的可用币种列表
AVAILABLE_BINANCE_PERPETUALS = [
    "1INCHUSDT", "AAVEUSDT", "ACAUSDT", "ACHUSDT", "ACMUSDT", "ADAUSDT", "ADXUSDT", "AERGOUSDT", "AGIXUSDT", "AIUSDT",
    "ALGOUSDT", "ALICEUSDT", "ALPHAUSDT", "ALPINEUSDT", "AMBUSDT", "ARPAUSDT", "ARUSDT", "ASRUSDT", "ATAUSDT", "ATOMUSDT",
    "AUCTIONUSDT", "AVAXUSDT", "AXLUSDT", "AXSUSDT", "BAKEUSDT", "BALUSDT", "BANDUSDT", "BATUSDT", "BCHUSDT", "BELUSDT",
    "BNTUSDT", "BNXUSDT", "BTCUSDT", "BTSUSDT", "BTTCUSDT", "BTTUSDT", "BURGERUSDT", "BUSDUSDT", "C98USDT", "CELOUSDT",
    "CELRUSDT", "CTSIUSDT", "CVCUSDT", "CVXUSDT", "DASHUSDT", "DEFIUSDT", "DEGOUSDT", "DENTUSDT", "DFUSDT", "DGBUSDT",
    "DODOUSDT", "DOGEUSDT", "DOTUSDT", "DUSDT", "DYDXUSDT", "EGLDUSDT", "ETCUSDT", "ETHUSDT", "FETUSDT", "FILUSDT",
    "FIOUSDT", "FLOWUSDT", "FLUXUSDT", "FORTHUSDT", "FORUSDT", "FRONTUSDT", "FTMUSDT", "FXSUSDT", "GALAUSDT", "GHSTUSDT",
    "GLMUSDT", "GRTUSDT", "GTCUSDT", "GTMUSDT", "HARDUSDT", "HBARUSDT", "HFTUSDT", "HIFIUSDT", "HIGHUSDT", "HOTUSDT",
    "ICPUSDT", "ICXUSDT", "IDEXUSDT", "IDUSDT", "IMXUSDT", "INJUSDT", "IOSTUSDT", "IOTAUSDT", "JUVUSDT", "KAVAUSDT",
    "KEYUSDT", "KLAYUSDT", "KSMUSDT", "LDOUSDT", "LENDUSDT", "LINAUSDT", "LINKUSDT", "LISTUSDT", "LITUSDT", "MASKUSDT",
    "MATICUSDT", "MAVUSDT", "MDTUSDT", "MDXUSDT", "METISUSDT", "MINAUSDT", "MKRUSDT", "MLNUSDT", "MOVRUSDT", "MTLUSDT",
    "MULTIUSDT", "NANOUSDT", "NTRNUSDT", "OAXUSDT", "OGNUSDT", "OGUSDT", "OMGUSDT", "OMNIUSDT", "ONEUSDT", "ONTUSDT",
    "OPUSDT", "ORBSUSDT", "OXTUSDT", "PARAUSDT", "PENDLEUSDT", "PONDUUSDT", "PORTOUSDT", "POWRUSDT", "PRIVUSDT", "PROSUSDT",
    "PSGUSDT", "PUNDIXUSDT", "PYRUSDT", "QIUSDT", "QNTUSDT", "QTUMUSDT", "RAREUSDT", "RAYUSDT", "RDNTUSDT", "RNDRUSDT",
    "ROSEUSDT", "RPLUSDT", "RSRUSDT", "RUNEUSDT", "RVNUSDT", "SANDUSDT", "SANTOSUSDT", "SCRTUSDT", "SCUSDT", "SFPUSDT",
    "SKLUSDT", "SLPUSDT", "SNXUSDT", "SOLUSDT", "SPELLUSDT", "SRMUSDT", "STORJUSDT", "STPTUSDT", "STXUSDT", "SUSHIUSDT",
    "SYNUSDT", "THETAUSDT", "TLMUSDT", "TMTUSDT", "TRUUSDT", "TRXUSDT", "TUSDT", "TUSDUSDT", "TVKUSDT", "TYTEUSDT",
    "UMAUSDT", "WAVESUSDT", "WAXPUSDT", "WOOUSDT", "XECUSDT", "XEMUSDT", "XLMUSDT", "XRPUSDT", "XTZUSDT", "XVGUSDT",
    "YFIUSDT", "YGGUSDT", "ZECUSDT", "ZENUSDT"
]

# 保持向后兼容的旧名称
BINANCE_PERPETUALS = AVAILABLE_BINANCE_PERPETUALS


def get_tradingview_symbols(limit: int = 50) -> list:
    """
    获取TradingView格式的币种符号

    Args:
        limit: 返回数量限制

    Returns:
        TradingView格式符号列表,如 ["BINANCE:BTCUSDT", "BINANCE:ETHUSDT", ...]
    """
    symbols = AVAILABLE_BINANCE_PERPETUALS[:limit]
    return [f"BINANCE:{s}" for s in symbols]
