#!/bin/bash
# Move unreferenced documents to trash folder

mkdir -p trash/archive_docs

mv "AIJIAOYI_COMPLETE_FINAL.md" trash/archive_docs/
mv "AIJIAOYI_FINAL_REPORT.md" trash/archive_docs/
mv "API_FIXES_SUMMARY.md" trash/archive_docs/
mv "API_TEST_REPORT.md" trash/archive_docs/
mv "BACKEND_RESTART_COMPLETE.md" trash/archive_docs/
mv "BINANCE_GAINER_FALLBACK_SOLUTION.md" trash/archive_docs/
mv "BINANCE_RESTRICTION_SOLUTION.md" trash/archive_docs/
mv "CONNECTION_STATUS.md" trash/archive_docs/
mv "DATABASE_SCHEMA.md" trash/archive_docs/
mv "DATA_STORAGE_POLICY.md" trash/archive_docs/
mv "DEPLOYMENT_SUCCESS.md" trash/archive_docs/
mv "DOCKER_INSTALL_GUIDE.md" trash/archive_docs/
mv "DOCKER_SELENIUM_COMPLETE.md" trash/archive_docs/
mv "EXCHANGE_CREDENTIALS_FEATURE.md" trash/archive_docs/
mv "FINAL_SUMMARY.md" trash/archive_docs/
mv "FIXES_SUMMARY.md" trash/archive_docs/
mv "FRONTEND_FIX_SUCCESS.md" trash/archive_docs/
mv "FRONTEND_TEST_REPORT.md" trash/archive_docs/
mv "FRONTENT_API_FIX_COMPLETE.md" trash/archive_docs/
mv "FUTURES_API_IMPLEMENTATION.md" trash/archive_docs/
mv "FUTURES_ONLY_COMPLETE.md" trash/archive_docs/
mv "GAINERS_DATA_FIX_COMPLETE.md" trash/archive_docs/
mv "GAINER_HISTORY_REDIS_STRUCTURE.md" trash/archive_docs/
mv "GAINER_TABLE_FIX_COMPLETE.md" trash/archive_docs/
mv "HAMA_15M_FIX_COMPLETE.md" trash/archive_docs/
mv "HAMA_ALGORITHM_FIXED.md" trash/archive_docs/
mv "HAMA_ALGORITHM_SUCCESS.md" trash/archive_docs/
mv "HAMA_API_FIX_COMPLETE.md" trash/archive_docs/
mv "HAMA_AUTO_MONITOR_GUIDE.md" trash/archive_docs/
mv "HAMA_AUTO_MONITOR_MYSQL.md" trash/archive_docs/
mv "HAMA_BRAVE_AUTO_LOGIN_COMPLETE.md" trash/archive_docs/
mv "HAMA_BRAVE_MONITOR_COMPLETE.md" trash/archive_docs/
mv "HAMA_BRAVE_ONLY.md" trash/archive_docs/
mv "HAMA_CACHE_AUTO_UPDATE.md" trash/archive_docs/
mv "HAMA_CACHE_CONFIG.md" trash/archive_docs/
mv "HAMA_CACHE_EXPLANATION.md" trash/archive_docs/
mv "HAMA_CACHE_SUCCESS.md" trash/archive_docs/
mv "HAMA_CROSS_DISPLAY_ISSUE.md" trash/archive_docs/
mv "HAMA_EMA20_SUCCESS.md" trash/archive_docs/
mv "HAMA_EMAIL_INTEGRATION_COMPLETE.md" trash/archive_docs/
mv "HAMA_EMAIL_NOTIFICATION_GUIDE.md" trash/archive_docs/
mv "HAMA_FIX.md" trash/archive_docs/
mv "HAMA_FIX_FINAL.md" trash/archive_docs/
mv "HAMA_FRONTEND_INTEGRATION_COMPLETE.md" trash/archive_docs/
mv "HAMA_MARKET_FRONTEND_FIX.md" trash/archive_docs/
mv "HAMA_MONITOR_COMPLETE.md" trash/archive_docs/
mv "HAMA_MONITOR_RUNNING.md" trash/archive_docs/
mv "HAMA_NO_LOGIN_COMPLETE.md" trash/archive_docs/
mv "HAMA_ON_DEMAND.md" trash/archive_docs/
mv "HAMA_PRICE_FIX.md" trash/archive_docs/
mv "HAMA_RIGHT_PANEL_OCR.md" trash/archive_docs/
mv "HAMA_SCREENSHOT_DEBUG.md" trash/archive_docs/
mv "HAMA_SCREENSHOT_DISPLAY.md" trash/archive_docs/
mv "HAMA_SCREENSHOT_DISPLAY_FIX.md" trash/archive_docs/
mv "HAMA_SCREENSHOT_FIX.md" trash/archive_docs/
mv "HAMA_SCREENSHOT_TOGGLE.md" trash/archive_docs/
mv "HAMA_SIGNAL_DISPLAY_FIX.md" trash/archive_docs/
mv "HAMA_SMART_EMAIL_NOTIFICATION.md" trash/archive_docs/
mv "HAMA_SMART_REFRESH_COMPLETE.md" trash/archive_docs/
mv "HAMA_SQLITE_PRIORITY.md" trash/archive_docs/
mv "HAMA_SYMBOLS_REVERT.md" trash/archive_docs/
mv "HAMA_TEST_REPORT.md" trash/archive_docs/
mv "HAMA_TEST_SUMMARY_20260118.md" trash/archive_docs/
mv "HAMA_WORKER_INTEGRATION.md" trash/archive_docs/
mv "HYBRID_DEPLOYMENT_GUIDE.md" trash/archive_docs/
mv "KLINE_FIX_SUMMARY.md" trash/archive_docs/
mv "MULTI_EXCHANGE_COMPARISON.md" trash/archive_docs/
mv "MULTI_EXCHANGE_PAGE_SUCCESS.md" trash/archive_docs/
mv "MYSQL_SETUP_GUIDE.md" trash/archive_docs/
mv "OCR_TEST_REPORT.md" trash/archive_docs/
mv "PROXY_CONFIG_COMPLETE.md" trash/archive_docs/
mv "PROXY_CONFIG_FIXED.md" trash/archive_docs/
mv "PROXY_CONFIG_RESULT.md" trash/archive_docs/
mv "PROXY_CONFIG_SUCCESS.md" trash/archive_docs/
mv "REALTIME_PRICE_SOLUTION.md" trash/archive_docs/
mv "REALTIME_PRICE_SUCCESS.md" trash/archive_docs/
mv "REDIS_AND_BRAVE_SETUP.md" trash/archive_docs/
mv "REDIS_DEPLOYMENT.md" trash/archive_docs/
mv "REDIS_SCHEDULER_GUIDE.md" trash/archive_docs/
mv "REDIS_SUCCESS_REPORT.md" trash/archive_docs/
mv "RESTART_GUIDE.md" trash/archive_docs/
mv "SCREENSHOT_CACHE_GUIDE.md" trash/archive_docs/
mv "SCREENSHOT_FIX_GUIDE.md" trash/archive_docs/
mv "SELENIUM_SETUP_COMPLETE.md" trash/archive_docs/
mv "SMART_MONITOR_COMPLETE.md" trash/archive_docs/
mv "SNTAX_ERROR_FIXED.md" trash/archive_docs/
mv "SQLITE_THREAD_FIX.md" trash/archive_docs/
mv "SSE_ALL_COINS_UPDATE_SUCCESS.md" trash/archive_docs/
mv "SSE_FINAL_EXPLANATION.md" trash/archive_docs/
mv "SSE_FINAL_FIX_REPORT.md" trash/archive_docs/
mv "SSE_NGINX_FIX_SUCCESS.md" trash/archive_docs/
mv "TIMEOUT_FIX_COMPLETE.md" trash/archive_docs/
mv "TRADINGVIEW_AS_DATASOURCE.md" trash/archive_docs/
mv "TRADINGVIEW_COIN_LEVEL_CACHE_COMPLETE.md" trash/archive_docs/
mv "TRADINGVIEW_COMPLETE.md" trash/archive_docs/
mv "TRADINGVIEW_COOKIES.md" trash/archive_docs/
mv "TRADINGVIEW_INTEGRATION_COMPLETE.md" trash/archive_docs/
mv "TRADINGVIEW_PLAYWRIGHT_IMPLEMENTATION.md" trash/archive_docs/
mv "TRADINGVIEW_PYPPETEER_IMPLEMENTATION.md" trash/archive_docs/
mv "TRADINGVIEW_SCANNER_ACCESS_GUIDE.md" trash/archive_docs/
mv "TRADINGVIEW_SCANNER_AUTO_HAMA.md" trash/archive_docs/
mv "TRADINGVIEW_SCANNER_DATA_TEST_REPORT.md" trash/archive_docs/
mv "TRADINGVIEW_SCANNER_FINAL_SUCCESS.md" trash/archive_docs/
mv "TRADINGVIEW_SCANNER_FRONTEND_INTEGRATION_COMPLETE.md" trash/archive_docs/
mv "TRADINGVIEW_SCANNER_HAMA_FEATURE_COMPLETE.md" trash/archive_docs/
mv "TRADINGVIEW_SCANNER_HAMA_RESTORED.md" trash/archive_docs/
mv "TRADINGVIEW_SCANNER_HAMA_STATUS_UPDATE.md" trash/archive_docs/
mv "TRADINGVIEW_SCANNER_INTEGRATION_SUCCESS.md" trash/archive_docs/
mv "TRADINGVIEW_SCANNER_MA100_COLUMN.md" trash/archive_docs/
mv "TRADINGVIEW_SCANNER_PAGE_READY.md" trash/archive_docs/
mv "TRADINGVIEW_SCANNER_REDIS_CACHE_SUCCESS.md" trash/archive_docs/
mv "TRADINGVIEW_SCANNER_SUCCESS.md" trash/archive_docs/
mv "TRADINGVIEW_SCANNER_TABLE_SIMPLIFIED.md" trash/archive_docs/
mv "TRADINGVIEW_SCANNER_THREE_MODES_TEST.md" trash/archive_docs/
mv "TRADINGVIEW_WATCHLIST_API_COMPLETE.md" trash/archive_docs/
mv "TRADINGVIEW_WATCHLIST_GUIDE.md" trash/archive_docs/
mv "UPDATE_HAMA_MONITOR.md" trash/archive_docs/
mv "VPN_PROXY_SUCCESS.md" trash/archive_docs/
mv "启动脚本使用指南.md" trash/archive_docs/
